image: node:14.15.1

stages:
  - test

Lint and Tests:
  stage: test
  cache:
    key: "dependencies"
    paths:
      - node_modules/
  script:
    - yarn install
    - yarn lint
    - echo "LINT SUCCESS"
    - yarn test
    - echo "TEST SUCCESS"
  only:
    - merge_requests